# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='golf_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Golf Course Name', max_length=100)),
                ('par', models.IntegerField()),
                ('length', models.IntegerField()),
                ('hole_1_par', models.IntegerField()),
                ('hole_2_par', models.IntegerField()),
                ('hole_3_par', models.IntegerField()),
                ('hole_4_par', models.IntegerField()),
                ('hole_5_par', models.IntegerField()),
                ('hole_6_par', models.IntegerField()),
                ('hole_7_par', models.IntegerField()),
                ('hole_8_par', models.IntegerField()),
                ('hole_9_par', models.IntegerField()),
                ('hole_10_par', models.IntegerField()),
                ('hole_11_par', models.IntegerField()),
                ('hole_12_par', models.IntegerField()),
                ('hole_13_par', models.IntegerField()),
                ('hole_14_par', models.IntegerField()),
                ('hole_15_par', models.IntegerField()),
                ('hole_16_par', models.IntegerField()),
                ('hole_17_par', models.IntegerField()),
                ('hole_18_par', models.IntegerField()),
                ('hole_1_yard', models.IntegerField()),
                ('hole_2_yard', models.IntegerField()),
                ('hole_3_yard', models.IntegerField()),
                ('hole_4_yard', models.IntegerField()),
                ('hole_5_yard', models.IntegerField()),
                ('hole_6_yard', models.IntegerField()),
                ('hole_7_yard', models.IntegerField()),
                ('hole_8_yard', models.IntegerField()),
                ('hole_9_yard', models.IntegerField()),
                ('hole_10_yard', models.IntegerField()),
                ('hole_11_yard', models.IntegerField()),
                ('hole_12_yard', models.IntegerField()),
                ('hole_13_yard', models.IntegerField()),
                ('hole_14_yard', models.IntegerField()),
                ('hole_15_yard', models.IntegerField()),
                ('hole_16_yard', models.IntegerField()),
                ('hole_17_yard', models.IntegerField()),
                ('hole_18_yard', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='golf_round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hole_1_score', models.IntegerField()),
                ('hole_2_score', models.IntegerField()),
                ('hole_3_score', models.IntegerField()),
                ('hole_4_score', models.IntegerField()),
                ('hole_5_score', models.IntegerField()),
                ('hole_6_score', models.IntegerField()),
                ('hole_7_score', models.IntegerField()),
                ('hole_8_score', models.IntegerField()),
                ('hole_9_score', models.IntegerField()),
                ('hole_10_score', models.IntegerField()),
                ('hole_11_score', models.IntegerField()),
                ('hole_12_score', models.IntegerField()),
                ('hole_13_score', models.IntegerField()),
                ('hole_14_score', models.IntegerField()),
                ('hole_15_score', models.IntegerField()),
                ('hole_16_score', models.IntegerField()),
                ('hole_17_score', models.IntegerField()),
                ('hole_18_score', models.IntegerField()),
                ('golf_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database1.golf_course')),
                ('golfer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('status', models.CharField(blank=True, choices=[('g', 'golfer'), ('c', 'coach')], default='g', max_length=2)),
            ],
            options={
                'ordering': ['team', 'user', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter team name', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database1.Team'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
