# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0003_auto_20171129_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='name', help_text='Enter full name', max_length=30),
        ),
    ]
