# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0006_auto_20171129_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AlterField(
            model_name='golf_round',
            name='golfer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database1.Profile'),
        ),
    ]
