# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 01:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0011_auto_20171202_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golf_round',
            name='golfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
