# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0012_auto_20171203_0125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='golf_round',
            new_name='golfround',
        ),
    ]
