# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0016_auto_20171206_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golf_course',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
