# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0005_remove_profile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
