# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0013_auto_20171203_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfround',
            name='date',
            field=models.DateField(help_text='MM/DD/YYYY'),
        ),
    ]
