# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0014_auto_20171203_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='golf_course',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
