# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0018_auto_20171206_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfround',
            name='fairways',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='golfround',
            name='greens',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='golfround',
            name='putts',
            field=models.IntegerField(default=36),
        ),
    ]
