# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0019_auto_20171207_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfround',
            name='putts',
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_10_putts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_11_putts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_12_putts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_13_putts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_14_putts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_15_putts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_16_putts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_17_putts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_18_putts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_1_putts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_2_putts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_3_putts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_4_putts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_5_putts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_6_putts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_7_putts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_8_putts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='golfround',
            name='hole_9_putts',
            field=models.IntegerField(default=2),
        ),
    ]
